export const BUSINESS = {
  name: 'Houston Handy Pros',
  phone: '(713) 555-0190',
  phoneHref: 'tel:+17135550190',
  email: 'hello@houstonhandypros.com',
  address: 'Houston, TX 77002',
  hours: 'Mon–Sat 7am–7pm',
  license: 'TCLP #12345678',
  tagline: "Houston's Most Trusted Handyman Service",
  founded: 2015,
  jobsCompleted: 3200,
  rating: 4.9,
  reviewCount: 847,
};

export const SERVICES = [
  {
    id: 'carpentry',
    title: 'Carpentry & Woodwork',
    icon: 'Hammer',
    description: 'Custom trim, door repairs, cabinet installation, and finish carpentry.',
    priceRange: '$75–$250',
    jobs: ['Door installation & repair', 'Cabinet repair & installation', 'Crown molding & trim', 'Deck repair', 'Custom shelving'],
  },
  {
    id: 'plumbing',
    title: 'Plumbing Repairs',
    icon: 'Wrench',
    description: 'Leak fixes, faucet replacement, toilet repair, and minor plumbing work.',
    priceRange: '$85–$300',
    jobs: ['Faucet replacement', 'Toilet repair & replacement', 'Leak detection & repair', 'Drain clearing', 'Shut-off valve replacement'],
  },
  {
    id: 'electrical',
    title: 'Electrical (Minor)',
    icon: 'Zap',
    description: 'Outlet replacement, fixture installation, ceiling fans, and light switches.',
    priceRange: '$75–$200',
    jobs: ['Outlet & switch replacement', 'Ceiling fan installation', 'Light fixture installation', 'GFCI outlet installation', 'Doorbell repair'],
  },
  {
    id: 'drywall',
    title: 'Drywall & Painting',
    icon: 'PaintBucket',
    description: 'Patch holes, texture matching, interior painting, and surface prep.',
    priceRange: '$100–$400',
    jobs: ['Drywall patch & repair', 'Texture matching', 'Interior painting', 'Popcorn ceiling removal', 'Caulking & sealing'],
  },
  {
    id: 'flooring',
    title: 'Flooring Installation',
    icon: 'Grid3X3',
    description: 'Hardwood, tile, LVP, and carpet installation and repair.',
    priceRange: '$150–$600',
    jobs: ['Hardwood repair & refinishing', 'Tile installation & repair', 'LVP/laminate installation', 'Carpet repair', 'Subfloor repair'],
  },
  {
    id: 'pressure-washing',
    title: 'Pressure Washing',
    icon: 'Droplets',
    description: 'Driveways, fences, decks, sidewalks, and exterior surfaces.',
    priceRange: '$100–$350',
    jobs: ['Driveway & sidewalk washing', 'Deck & patio cleaning', 'Fence washing', 'House exterior washing', 'Concrete stain removal'],
  },
  {
    id: 'fence',
    title: 'Fence & Gate Repair',
    icon: 'Shield',
    description: 'Wood fence repair, gate alignment, post replacement, and staining.',
    priceRange: '$100–$450',
    jobs: ['Fence board replacement', 'Post repair & replacement', 'Gate alignment & hardware', 'Fence staining & sealing', 'New fence sections'],
  },
  {
    id: 'assembly',
    title: 'Furniture Assembly',
    icon: 'Package',
    description: 'IKEA, flat-pack furniture, gym equipment, and outdoor furniture.',
    priceRange: '$65–$200',
    jobs: ['IKEA & flat-pack assembly', 'Office furniture setup', 'Outdoor furniture assembly', 'Gym equipment assembly', 'Bed frame assembly'],
  },
  {
    id: 'tv-mounting',
    title: 'TV Mounting & Smart Home',
    icon: 'Monitor',
    description: 'TV wall mounting, cord concealment, and smart device installation.',
    priceRange: '$75–$250',
    jobs: ['TV wall mounting', 'Cord management & concealment', 'Smart thermostat installation', 'Doorbell camera installation', 'Sound bar mounting'],
  },
  {
    id: 'maintenance',
    title: 'Seasonal Maintenance',
    icon: 'Calendar',
    description: 'Seasonal home check-ups, HVAC filter changes, caulking, and weatherizing.',
    priceRange: 'Plans from $99/mo',
    jobs: ['AC filter replacement', 'Weatherstripping', 'Gutter cleaning', 'Smoke detector testing', 'Seasonal caulking'],
  },
  {
    id: 'commercial',
    title: 'Commercial Services',
    icon: 'Building2',
    description: 'Office repairs, retail maintenance, property management support.',
    priceRange: 'Custom quote',
    jobs: ['Office repairs & maintenance', 'Retail fixture installation', 'Property management support', 'Multi-unit repairs', 'ADA compliance work'],
  },
];

export const NEIGHBORHOODS = [
  'The Heights', 'Montrose', 'River Oaks', 'West University', 'Bellaire',
  'Memorial', 'Meyerland', 'Pearland', 'Sugar Land', 'Katy',
  'The Woodlands', 'Spring', 'Humble', 'Pasadena', 'Friendswood',
  'Missouri City', 'Stafford', 'Galleria', 'Midtown', 'EaDo',
  'Garden Oaks', 'Oak Forest', 'Timbergrove', 'Tanglewood', 'Briargrove',
];

export const FAQS = [
  {
    q: 'Are you licensed and insured?',
    a: 'Yes. Houston Handy Pros is fully licensed (TCLP #12345678), bonded, and carries $1M in general liability insurance. We carry workers\' compensation on all technicians.',
  },
  {
    q: 'How quickly can you come out?',
    a: 'Most jobs can be booked within 24–48 hours. For urgent repairs, call us directly and we\'ll do our best to dispatch same-day.',
  },
  {
    q: 'Do you charge for estimates?',
    a: 'Standard estimates are free. For larger projects requiring significant scoping time, a $49 site visit fee applies — credited back when you book.',
  },
  {
    q: 'What forms of payment do you accept?',
    a: 'We accept all major credit cards, Apple Pay, Google Pay, Venmo, and check. A 50% deposit is required for jobs over $300.',
  },
  {
    q: 'Do you guarantee your work?',
    a: 'Absolutely. All labor comes with a 1-year workmanship guarantee. If something we fix fails within a year, we come back at no charge.',
  },
  {
    q: 'What areas do you serve?',
    a: 'We serve Houston and all surrounding areas including Sugar Land, Katy, Pearland, The Woodlands, and more — within a 40-mile radius of downtown Houston.',
  },
];

export const REVIEWS = [
  {
    name: 'Sarah M.',
    neighborhood: 'The Heights',
    rating: 5,
    text: 'Marcus fixed our leaky faucet AND noticed our garbage disposal was about to give out. Saved us a flood. Will 100% use again.',
    service: 'Plumbing Repair',
    date: '2 weeks ago',
  },
  {
    name: 'David R.',
    neighborhood: 'Sugar Land',
    rating: 5,
    text: 'Mounted three TVs and hid all the cords. Looks like a million bucks. On time, professional, and reasonably priced.',
    service: 'TV Mounting',
    date: '1 month ago',
  },
  {
    name: 'Jennifer T.',
    neighborhood: 'Katy',
    rating: 5,
    text: 'As a property manager I need reliable people fast. Houston Handy Pros has become my go-to. They\'ve done 12 jobs for me across 3 properties.',
    service: 'Commercial Services',
    date: '3 weeks ago',
  },
  {
    name: 'Michael K.',
    neighborhood: 'Montrose',
    rating: 5,
    text: 'Repaired a huge section of fence that the last storm took out. Clean work, fair price, and done in one day.',
    service: 'Fence Repair',
    date: '1 week ago',
  },
  {
    name: 'Amanda L.',
    neighborhood: 'West University',
    rating: 5,
    text: 'Drywall patch looks perfect — you literally cannot tell it was ever there. Really skilled team.',
    service: 'Drywall & Painting',
    date: '2 months ago',
  },
  {
    name: 'Carlos V.',
    neighborhood: 'Pearland',
    rating: 5,
    text: 'Signed up for the quarterly maintenance plan. Best $199 I spend. They catch small things before they become expensive problems.',
    service: 'Maintenance Plan',
    date: '3 months ago',
  },
];

export const PRICING_PLANS = [
  {
    name: 'Basic',
    price: '$99',
    period: '/month',
    description: 'Essential maintenance for busy homeowners',
    features: [
      '1 maintenance visit per quarter',
      'AC filter replacement',
      'Smoke & CO detector check',
      'Caulking inspection',
      '10% off all additional services',
      'Priority scheduling',
    ],
    cta: 'Start Basic Plan',
    popular: false,
  },
  {
    name: 'Pro',
    price: '$199',
    period: '/month',
    description: 'Most popular — comprehensive home care',
    features: [
      '1 visit per month',
      'All Basic features',
      'Gutter cleaning (2x/year)',
      'Pressure washing (1x/year)',
      '15% off all additional services',
      'Same-day scheduling',
      'Dedicated technician',
    ],
    cta: 'Start Pro Plan',
    popular: true,
  },
  {
    name: 'Property Manager',
    price: 'Custom',
    period: '',
    description: 'Multi-unit & commercial properties',
    features: [
      'Volume pricing',
      'Multiple property management',
      'Dedicated account manager',
      '20% off all services',
      '24/7 emergency line',
      'Monthly reporting',
    ],
    cta: 'Get Custom Quote',
    popular: false,
  },
];
